server.port: 9090
spring:
  devtools:
    add-properties: @devTools@
  resources:
    add-mappings: false
  datasource:
    url: @dbUrl@
    username: @dbUser@
    password: @dbPasswd@
    initialization-mode: never
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob.non_contextual_creation: true

  profiles:
    active: @env@